version: "3"

services:
  apache_php:
    build: ./
    container_name: apache_php
    ports:
      - "1414:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql_server
    networks:
      - warlord_realm_web

  mysql_server:
    image: mysql:8.0.44-debian
    container_name: mysql_server
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: warlordnetworkroot
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - warlord_realm_web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "1515:80"
    environment:
      PMA_HOST: mysql_server
      # PMA_USER: root
      # PMA_PASSWORD: warlordnetworkroot
    depends_on:
      - mysql_server
    networks:
      - warlord_realm_web

volumes:
  mysql_data:

networks:
  warlord_realm_web:
    driver: bridge
